// evolve-candidate SearchConfig — Iteration 000 (BASELINE)
// Clone of omega-marathon. This is the starting point for the evolution loop.
SearchConfig {
    id: "evolve-candidate",
    description: "Progressive evolution candidate — iteratively improved by automated loop.",
    lookahead_frames: 20.0,
    risk_weight_asteroid: 1.45,
    risk_weight_saucer: 2.05,
    risk_weight_bullet: 2.85,
    survival_weight: 2.05,
    aggression_weight: 0.5,
    fire_reward: 0.68,
    shot_penalty: 0.9,
    miss_fire_penalty: 1.2,
    action_penalty: 0.011,
    turn_penalty: 0.013,
    thrust_penalty: 0.012,
    center_weight: 0.52,
    edge_penalty: 0.36,
    speed_soft_cap: 3.95,
    fire_tolerance_bam: 7,
    fire_distance_px: 250.0,
    lurk_trigger_frames: 310,
    lurk_aggression_boost: 1.4,
},
