import type { ProofCoordinatorDO } from "./durable/coordinator";
import type { ClaimQueueMessage, ProofQueueMessage } from "./types";

export interface WorkerEnv {
  ASSETS: Fetcher;
  PROOF_QUEUE: Queue<ProofQueueMessage>;
  CLAIM_QUEUE: Queue<ClaimQueueMessage>;
  PROOF_COORDINATOR: DurableObjectNamespace<ProofCoordinatorDO>;
  PROOF_ARTIFACTS: R2Bucket;
  LEADERBOARD_DB: D1Database;
  PROVER_BASE_URL: string;
  PROVER_API_KEY?: string;
  PROVER_ACCESS_CLIENT_ID?: string;
  PROVER_ACCESS_CLIENT_SECRET?: string;
  PROVER_EXPECTED_IMAGE_ID?: string;
  PROVER_HEALTH_CACHE_MS?: string;
  PROVER_POLL_INTERVAL_MS?: string;
  PROVER_POLL_TIMEOUT_MS?: string;
  PROVER_REQUEST_TIMEOUT_MS?: string;
  PROVER_POLL_BUDGET_MS?: string;
  MAX_TAPE_BYTES?: string;
  MAX_JOB_WALL_TIME_MS?: string;
  MAX_COMPLETED_JOBS?: string;
  COMPLETED_JOB_RETENTION_MS?: string;
  ALLOW_INSECURE_PROVER_URL?: string;
  RELAYER_URL?: string;
  RELAYER_API_KEY?: string;
  RELAYER_PLUGIN_ID?: string;
  RELAYER_REQUEST_TIMEOUT_MS?: string;
  SCORE_CONTRACT_ID?: string;
  LEADERBOARD_SYNC_CRON_ENABLED?: string;
  LEADERBOARD_SYNC_CRON_LIMIT?: string;
  LEADERBOARD_CATCHUP_INTERVAL_MINUTES?: string;
  LEADERBOARD_CATCHUP_WINDOW_LEDGERS?: string;
  LEADERBOARD_FORWARD_REPLAY_WINDOW_LEDGERS?: string;
  SMART_ACCOUNT_INDEXER_URL?: string;
  GALEXIE_SOURCE_MODE?: string;
  GALEXIE_DATASTORE_ROOT_PATH?: string;
  GALEXIE_DATASTORE_OBJECT_EXTENSION?: string;
  GALEXIE_API_BASE_URL?: string;
  GALEXIE_API_KEY?: string;
  GALEXIE_RPC_BASE_URL?: string;
  GALEXIE_REQUEST_TIMEOUT_MS?: string;
  GALEXIE_SCORE_EVENTS_PATH?: string;
  CLAIM_NETWORK_PASSPHRASE?: string;
}
